### ISSUE TITLE
Adding a model to Ollama

### ISSUE THREAD

**Issue by micuentadecasa** [CastawayEGR/openshift-ai-examples#1]
Hi @CastawayEGR , thanks for the manifest, it works ok, but it has no model loaded, how can I load nomic model for embedding in the manifest?

Regards.

**Comment by CastawayEGR** [comment]
You are welcome. Depending on your use case this could be as simple as manually running `ollama pull nomic-embed-text` from a shell session into the pod or you could make an API call to the `/api/pull` endpoint once the API is running. With the PVC it will be there even when the pod is restarted.

I personally just use Open WebUI to pull models I'd like in my environment.

If you'd like to do this automatically upon creation, I'd probably customize the base image when a script that automatically pulls it before starting ollama.

**Comment by micuentadecasa** [comment]
Hi @CastawayEGR , I made it work with this command (I put below in case someone need it)

oc exec svc/ollama -- ollama pull nomic-embed-text
oc exec svc/ollama -- ollama pull mistral:7b

but of course it will be great if it can be included in the manifest file, so it is easier to automate. Anyway great work @CastawayEGR , close this issue if you want.
